package com.example.MovieRentalLab.mybatis.dao;

import com.example.MovieRentalLab.mybatis.model.Award;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface AwardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AWARD
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AWARD
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    int insert(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AWARD
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    Award selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AWARD
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    List<Award> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AWARD
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    int updateByPrimaryKey(Award record);
}