package com.example.MovieRentalLab.mybatis.dao;

import com.example.MovieRentalLab.mybatis.model.ClientMovie;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ClientMovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT_MOVIE
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    int insert(ClientMovie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT_MOVIE
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    List<ClientMovie> selectAll();
}