package com.example.MovieRentalLab.mybatis.dao;

import com.example.MovieRentalLab.mybatis.model.Client;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    Client selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    List<Client> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLIENT
     *
     * @mbg.generated Tue May 04 00:12:11 EEST 2021
     */
    int updateByPrimaryKey(Client record);
}