package com.example.MovieRentalLab.mybatis.model;

import com.example.MovieRentalLab.entities.Client;
import lombok.Getter;
import lombok.Setter;

public class Award {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AWARD.ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AWARD.AWARD_TYPE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Integer awardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AWARD.DISCOUNT
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Double discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AWARD.OFFICIAL_NAME
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private String officialName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AWARD.CLIENT_ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Integer clientId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AWARD.ID
     *
     * @return the value of PUBLIC.AWARD.ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AWARD.ID
     *
     * @param id the value for PUBLIC.AWARD.ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AWARD.AWARD_TYPE
     *
     * @return the value of PUBLIC.AWARD.AWARD_TYPE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Integer getAwardType() {
        return awardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AWARD.AWARD_TYPE
     *
     * @param awardType the value for PUBLIC.AWARD.AWARD_TYPE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setAwardType(Integer awardType) {
        this.awardType = awardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AWARD.DISCOUNT
     *
     * @return the value of PUBLIC.AWARD.DISCOUNT
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AWARD.DISCOUNT
     *
     * @param discount the value for PUBLIC.AWARD.DISCOUNT
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AWARD.OFFICIAL_NAME
     *
     * @return the value of PUBLIC.AWARD.OFFICIAL_NAME
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public String getOfficialName() {
        return officialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AWARD.OFFICIAL_NAME
     *
     * @param officialName the value for PUBLIC.AWARD.OFFICIAL_NAME
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setOfficialName(String officialName) {
        this.officialName = officialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AWARD.CLIENT_ID
     *
     * @return the value of PUBLIC.AWARD.CLIENT_ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AWARD.CLIENT_ID
     *
     * @param clientId the value for PUBLIC.AWARD.CLIENT_ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    @Getter
    @Setter
    private Client client;
}