package com.example.MovieRentalLab.mybatis.model;

import com.example.MovieRentalLab.entities.Award;
import com.example.MovieRentalLab.entities.Movie;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import java.util.List;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.EMAIL
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.PHONE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.USERNAME
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.ID
     *
     * @return the value of PUBLIC.CLIENT.ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.ID
     *
     * @param id the value for PUBLIC.CLIENT.ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.EMAIL
     *
     * @return the value of PUBLIC.CLIENT.EMAIL
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.EMAIL
     *
     * @param email the value for PUBLIC.CLIENT.EMAIL
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.PHONE
     *
     * @return the value of PUBLIC.CLIENT.PHONE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.PHONE
     *
     * @param phone the value for PUBLIC.CLIENT.PHONE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.USERNAME
     *
     * @return the value of PUBLIC.CLIENT.USERNAME
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.USERNAME
     *
     * @param username the value for PUBLIC.CLIENT.USERNAME
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    @Getter @Setter
    private List<Award> awards;

    @Getter @Setter
    private List<Movie> movies;
}