package com.example.MovieRentalLab.mybatis.model;

public class ClientMovie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT_MOVIE.CLIENTS_ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Integer clientsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT_MOVIE.MOVIES_ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Integer moviesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT_MOVIE.CLIENTS_ID
     *
     * @return the value of PUBLIC.CLIENT_MOVIE.CLIENTS_ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Integer getClientsId() {
        return clientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT_MOVIE.CLIENTS_ID
     *
     * @param clientsId the value for PUBLIC.CLIENT_MOVIE.CLIENTS_ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setClientsId(Integer clientsId) {
        this.clientsId = clientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT_MOVIE.MOVIES_ID
     *
     * @return the value of PUBLIC.CLIENT_MOVIE.MOVIES_ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Integer getMoviesId() {
        return moviesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT_MOVIE.MOVIES_ID
     *
     * @param moviesId the value for PUBLIC.CLIENT_MOVIE.MOVIES_ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setMoviesId(Integer moviesId) {
        this.moviesId = moviesId;
    }
}