package com.example.MovieRentalLab.mybatis.model;

import com.example.MovieRentalLab.entities.Client;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;
import java.util.List;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.AVAILABILITY_END_DATE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Date availabilityEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.GENRE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Integer genre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.RELEASE_DATE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    private Date releaseDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.ID
     *
     * @return the value of PUBLIC.MOVIE.ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.ID
     *
     * @param id the value for PUBLIC.MOVIE.ID
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.AVAILABILITY_END_DATE
     *
     * @return the value of PUBLIC.MOVIE.AVAILABILITY_END_DATE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Date getAvailabilityEndDate() {
        return availabilityEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.AVAILABILITY_END_DATE
     *
     * @param availabilityEndDate the value for PUBLIC.MOVIE.AVAILABILITY_END_DATE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setAvailabilityEndDate(Date availabilityEndDate) {
        this.availabilityEndDate = availabilityEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.GENRE
     *
     * @return the value of PUBLIC.MOVIE.GENRE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Integer getGenre() {
        return genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.GENRE
     *
     * @param genre the value for PUBLIC.MOVIE.GENRE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setGenre(Integer genre) {
        this.genre = genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.NAME
     *
     * @return the value of PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.NAME
     *
     * @param name the value for PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.RELEASE_DATE
     *
     * @return the value of PUBLIC.MOVIE.RELEASE_DATE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.RELEASE_DATE
     *
     * @param releaseDate the value for PUBLIC.MOVIE.RELEASE_DATE
     *
     * @mbg.generated Tue May 04 00:20:10 EEST 2021
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    @Getter @Setter
    private List<Client> clients;

    public List<Client> getClients(){ return clients;}
}